language: php
php:
- '7.2'
- '7.3'
branches:
  only:
  - master
  - 1.0
env:
- LARAVEL_VERSION=5.6.*
- LARAVEL_VERSION=5.8.*
matrix:
  fast_finish: true
install:
- composer install
- composer require "laravel/framework:${LARAVEL_VERSION}"
after_success:
- travis_retry php vendor/bin/coveralls